services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432" # port mapping between host machine and container
    volumes: # distinguish between named volumes and bind mounts
      - postgres_data:/var/lib/postgresql #named volume for persisting data
      - ./sql:/sql # bind mount for persisting data
    healthcheck: # define a check after the container is up running
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      retries: 5
      timeout: 3s

volumes: # here is where named volume is created
  postgres_data:
